[ACNA-1304][WIP] App run auto watch/re-deployment of actions redeploys all
adobe/aio-lib-runtime pull request #75
Opened 2021-09-16 15:51 UTC by florind12

WIP. 

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-30 08:19 UTC, florind12 commented
Changes in dependency tree requires restart. 
Where is the best to put this info up ?

2021-09-30 08:21 UTC, florind12 commented
Tested this with symlink for the actions folder. Everything seems to be working as expected.

2021-10-06 14:05 UTC, shazron requested changes

2021-10-06 14:05 UTC, shazron commented on test/build.actions.test.js
> +test('should skip check for action built before while action filter', async () => {
better description for the test needed. maybe `should always zip files because the action because skipCheck=true`

2021-10-06 14:41 UTC, shazron commented on src/utils.js
> +function tryParseString (stringData) {
there is already utils.safeParse, can it not be used?

2021-11-01 12:54 UTC, shazron approved these changes

2021-11-01 12:54 UTC, shazron commented
Tested with https://github.com/adobe/aio-cli-plugin-app/pull/497, works ok now.

2021-11-02 09:56 UTC, sandeep-paliwal approved these changes
LGTM

2021-11-02 12:23 UTC, merged