bugfix: Support for concurrentActivations limit key.
adobe/aio-lib-runtime pull request #94
Opened 2022-03-02 06:24 UTC by florind12

## Description
The manifest spec limits keys we are supporting are:  

- timeout
- memorySize
- logSize
- concurrentActivations

This PR maps, concurrentActivations key to concurrency key. 

## Related Issue
https://github.com/adobe/aio-cli-plugin-app/issues/507

## Motivation and Context

## How Has This Been Tested?
unit tests
replication steps from the mentioned issue. 

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-03 04:43 UTC, sandeep-paliwal approved these changes
LGTM

2022-03-03 06:57 UTC, Himavanth commented
Hi @florind12 ,
There seems to be some ambiguity here about `concurrentActivations` being the same as `concurrency` .

The docs at https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#valid-limit-keys say `concurrentActivations` is supported and it is `per-namespace`.

The parsers in wskdeploy show `concurrentActivations` under `unsupported` category. https://github.com/apache/openwhisk-wskdeploy/blob/master/parsers/yamlparser.go#L64-L65
https://github.com/apache/openwhisk-wskdeploy/blob/master/parsers/manifest_parser.go#L810

Do you know if `concurrentActivations` is working with wskdeploy ?

2022-03-03 07:47 UTC, florind12 commented
@Himavanth 
Good observation. 
I suppose this is fine since the code changes gives room to use both keys:  `concurrentActivations` || `concurrency`
I think what matters is that Runtime API supports only the `concurrentActivations` key, this is the purpose of these code changes.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/74616552/156519540-661b57f4-8262-4330-b68e-bf28945a7445.png">
Adobe Runtime API: https://adobeioruntime.net/api/v1/docs/index.html?url=/api/v1/api-docs

2022-03-03 08:56 UTC, florind12 commented
@shazron @Himavanth 
New info: 
wskdeploy will parse the `concurrentActivations` key, but will ignore it:

`Warning: Action Limit [concurrentActivations] is currently not changeable. Ignoring...`

2022-03-15 14:53 UTC, shazron requested changes

2022-03-15 14:53 UTC, shazron commented on src/utils.js
> +      ...concurrencyLimit && { concurrency: concurrencyLimit }
can you express this in more approachable logic, for maintainability purposes

2022-03-17 19:13 UTC, shazron approved these changes

2022-03-17 19:14 UTC, merged